name             'webgrind-cookbook'
maintainer       'gregpalmier'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures webgrind-cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends		 'apt'
depends		 'build-essential'
depends		 'git'
depends		 'php'
depends		 'apache2'
